FROM python:3.10-slim

## Dockerfile disabled
## The project previously created a Dockerfile here, but the user requested
## not to use a Dockerfile. Keep this placeholder to avoid accidental builds.
## To re-enable, restore a valid Dockerfile.
