"""Support both auth methods

Revision ID: 026525d5c409
Revises: a9db35a73e1b
Create Date: 2025-10-20 00:01:29.501933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026525d5c409'
down_revision = 'a9db35a73e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
