"""add reset token

Revision ID: 157d06053aa6
Revises: 026525d5c409
Create Date: 2025-10-22 00:20:11.860644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157d06053aa6'
down_revision = '026525d5c409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_tokens_reset_code'), ['reset_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_reset_code'))
        batch_op.drop_column('reset_code_expires_at')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
