"""rm unuse relationship

Revision ID: 63b16323740d
Revises: 681bc624f728
Create Date: 2025-10-19 01:33:28.535568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b16323740d'
down_revision = '681bc624f728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
