"""rm unuse relationship

Revision ID: 681bc624f728
Revises: c733f1b0209f
Create Date: 2025-10-19 01:32:37.191747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681bc624f728'
down_revision = 'c733f1b0209f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
